### ISSUE TITLE
CrystalReportsNinja Database logon failed Windows OS

### ISSUE THREAD

**Issue by itsoftsaeed** [mhertzfeld/CrystalReportsNinja#60]
First try

[25-08-2022](https://github.com/rainforestnet/CrystalReportsNinja/issues/url) 16:58:04 Report loaded successfully
25-08-2022 16:58:04 Output Filename : test.pdf
25-08-2022 16:58:04 Output format : pdf
25-08-2022 16:58:04 Exception: Database logon failed.
25-08-2022 16:58:04 Inner Exception: System.Runtime.InteropServices.COMException (0x8004100F): Database logon failed.
at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
-------------------------------------------------------------------------------------------------------------------------
second try

25-08-2022	18:09:34	================== LoadReport, Output File and DB logion ===========
25-08-2022	18:09:34	Report news.rpt loaded successfully
25-08-2022	18:09:34	Output Filename : test.pdf
25-08-2022	18:09:34	Output Format : pdf
25-08-2022	18:09:34	Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
25-08-2022	18:09:34	
25-08-2022	18:09:34	================== ProcessParameters ===============================
25-08-2022	18:09:34	Number of Parameters detected in the report = 0
25-08-2022	18:09:34	
25-08-2022	18:09:34	================== STEP = PerformOutput ============================
25-08-2022	18:09:34	
25-08-2022	18:09:34	===================Logs and Errors =================================
25-08-2022	18:09:34	Message: Failed to open the connection.
news 12900_5760_{57B50DE2-FB79-4D16-B43C-F47FE03B5111}.rpt
25-08-2022	18:09:34	HResult: -2147221760
25-08-2022	18:09:34	Data: System.Collections.ListDictionaryInternal
25-08-2022	18:09:34	Inner Exception: System.Runtime.InteropServices.COMException (0x800002F4): Failed to open the connection.
news 12900_5760_{57B50DE2-FB79-4D16-B43C-F47FE03B5111}.rpt
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
25-08-2022	18:09:34	StackTrace:    at CrystalDecisions.ReportAppServer.ConvertDotNetToErom.ThrowDotNetException(Exception e)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export()
   at CrystalDecisions.CrystalReports.Engine.ReportDocument.Export()
   at CrystalReportsNinja.ReportProcessor.PerformOutput()
   at CrystalReportsNinja.ReportProcessor.Run()
25-08-2022	18:09:34	====================================================================

when I try to run with 32bit OS the report is working successfully, but try to run with 64Bit OS, the following error occurred Exception: Database logon failed...................., similarly I cannot deploy on remotely window server 2019 64Bit OS, same problem facing.... here try to connect with MYSQL database 
my parameters in Command Line are: 
D:\Web\xampp\htdocs\cr>CrystalReportsNinja -U"dw01_wit" -P"_khan&&bro" -F news.rpt -S"localhost" -D"dw01_wifaq" -O test.pdf -E pdf
OR
also try as given below
D:\Web\xampp\htdocs\cr>CrystalReportsNinja.exe -U dw01_wit -P password -F news.rpt -S localhost  -D dw01_wifaq -O test.pdf -E pdf

I try to connect with mysql database through ODBC 32bit drivers .......

When I try to run simple report without adding any table into the report ..... it connected successfully.
parameters in Command Line are:
CrystalReportsNinja -F r6.rpt -O test.pdf -E pdf
Report loaded successfully
Database Login done
Completed
![Screenshot_7](https://user-images.githubusercontent.com/11254651/186662869-5bc4ea24-5a68-4493-b637-72c77ddbd1d2.jpg)
[ninja-20220825165802.log](https://github.com/mhertzfeld/CrystalReportsNinja/files/9424551/ninja-20220825165802.log)

any one can help me, to solve this problem how connect with  CrystalReportsNinja, with credentials parameters , adding tables into the report through MYSQL odbc deriver.. ?

**Comment by weslynxt** [comment]
I have a similar error, I use an EC2 AWS server where my Mysql database is, also I have my ODB 32-bit configured with the AWS server, and I have configured the connection in my .rpt made in Crystal Report 2016, I have RunT 13.0.28 installed (use other runtime like 13.0.26) and I use the following command line:
.\CrystalReportsNinja.exe -F report.rpt -O report.pdf -E pdf -a "key:31"

The KEY thing, is my required field parameter to display the report result.

I don't use the parameters -U xxxxx -P xxxx -S xxxx since the .rpt file already has it configured, it is supposed to connect, but even when I pass those parameters it returns the same error:

```
.\CrystalReportsNinja.exe -F reporte.rpt -O reporte.pdf -E pdf -a "clave:31"
17-07-2023      20:49:25
17-07-2023      20:49:25        ================== LoadReport, Output File and DB logion ===========
17-07-2023      20:49:25        Report reporte.rpt loaded successfully
17-07-2023      20:49:25        Output Filename : reporte.pdf
17-07-2023      20:49:25        Output Format : pdf
17-07-2023      20:49:25        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: REPORTUSERNAME with Integrated Security = False
17-07-2023      20:49:26
17-07-2023      20:49:26        ================== ProcessParameters ===============================
17-07-2023      20:49:26        Number of Parameters detected in the report = 2
17-07-2023      20:49:26        Number of Parameters passed by the users script = 1
17-07-2023      20:49:26
17-07-2023      20:49:26        Applied Parameter 'clave' as MultiValue 'False'
17-07-2023      20:49:26        Discrete Parameter : clave = 31
17-07-2023      20:49:26        Single Value Parameter - Prompt = Especificar clave: - clave = 31
17-07-2023      20:49:26
17-07-2023      20:49:26        Skipped 'Pm-bills1.id' as MultiValue 'False' Parameter in SubReport = 'LISTAR_VEHICULOS' as its Linked to Main Report
17-07-2023      20:49:26
17-07-2023      20:49:26
17-07-2023      20:49:26        ================== STEP = PerformOutput ============================
17-07-2023      20:49:26
17-07-2023      20:49:26        ===================Logs and Errors =================================
17-07-2023      20:49:26        Message: No se pudo abrir la conexión.
reporte 2384_3944_{8809AD42-4D54-455E-8191-E0DFBBEE1F0F}.rpt
17-07-2023      20:49:26        HResult: -2147221760
17-07-2023      20:49:26        Data: System.Collections.ListDictionaryInternal
17-07-2023      20:49:26        Inner Exception: System.Runtime.InteropServices.COMException (0x800002F4): No se pudo abrir la conexión.
reporte 2384_3944_{8809AD42-4D54-455E-8191-E0DFBBEE1F0F}.rpt
   en CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   en CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
17-07-2023      20:49:26        StackTrace:    en CrystalDecisions.ReportAppServer.ConvertDotNetToErom.ThrowDotNetException(Exception e)
   en CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
   en CrystalDecisions.CrystalReports.Engine.FormatEngine.ExportToStream(ExportRequestContext reqContext)
   en CrystalDecisions.CrystalReports.Engine.FormatEngine.Export(ExportRequestContext reqContext)
   en CrystalDecisions.CrystalReports.Engine.FormatEngine.Export()
   en CrystalDecisions.CrystalReports.Engine.ReportDocument.Export()
   en CrystalReportsNinja.ReportProcessor.PerformOutput()
   en CrystalReportsNinja.ReportProcessor.Run()
17-07-2023      20:49:26        ====================================================================
Exception: No se pudo abrir la conexión.
reporte 2384_3944_{8809AD42-4D54-455E-8191-E0DFBBEE1F0F}.rpt
Inner Exception: System.Runtime.InteropServices.COMException (0x800002F4): No se pudo abrir la conexión.
reporte 2384_3944_{8809AD42-4D54-455E-8191-E0DFBBEE1F0F}.rpt
   en CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   en CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
```
If I pass the parameters -U -P:

```
 .\CrystalReportsNinja.exe -U administrator -P 343da333 -F reporte.rpt -O reporte.pdf -E pdf -a "clave:31"
17-07-2023      20:50:36
17-07-2023      20:50:36        ================== LoadReport, Output File and DB logion ===========
17-07-2023      20:50:37        Report reporte.rpt loaded successfully
17-07-2023      20:50:37        Output Filename : reporte.pdf
17-07-2023      20:50:37        Output Format : pdf
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:37        Logging into SQLDBNAME Database on SQLSERVERNAME with User id: adminw with Integrated Security = False
17-07-2023      20:50:38
17-07-2023      20:50:38        ================== ProcessParameters ===============================
17-07-2023      20:50:38        Number of Parameters detected in the report = 2
17-07-2023      20:50:38        Number of Parameters passed by the users script = 1
17-07-2023      20:50:38
17-07-2023      20:50:38        Applied Parameter 'clave' as MultiValue 'False'
17-07-2023      20:50:38        Discrete Parameter : clave = 31
17-07-2023      20:50:38        Single Value Parameter - Prompt = Especificar clave: - clave = 31
17-07-2023      20:50:38
17-07-2023      20:50:38        Skipped 'Pm-bills1.id' as MultiValue 'False' Parameter in SubReport = 'LISTAR_VEHICULOS' as its Linked to Main Report
17-07-2023      20:50:38
17-07-2023      20:50:38
17-07-2023      20:50:38        ================== STEP = PerformOutput ============================
17-07-2023      20:50:38
17-07-2023      20:50:38        ===================Logs and Errors =================================
17-07-2023      20:50:38        Message: No se pudo abrir la conexión.
reporte 20284_15032_{2FF0929E-00EF-4E59-93A2-E2F892898C23}.rpt
17-07-2023      20:50:38        HResult: -2147221760
17-07-2023      20:50:38        Data: System.Collections.ListDictionaryInternal
17-07-2023      20:50:38        Inner Exception: System.Runtime.InteropServices.COMException (0x800002F4): No se pudo abrir la conexión.
reporte 20284_15032_{2FF0929E-00EF-4E59-93A2-E2F892898C23}.rpt
   en CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   en CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
17-07-2023      20:50:38        StackTrace:    en CrystalDecisions.ReportAppServer.ConvertDotNetToErom.ThrowDotNetException(Exception e)
   en CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
   en CrystalDecisions.CrystalReports.Engine.FormatEngine.ExportToStream(ExportRequestContext reqContext)
   en CrystalDecisions.CrystalReports.Engine.FormatEngine.Export(ExportRequestContext reqContext)
   en CrystalDecisions.CrystalReports.Engine.FormatEngine.Export()
   en CrystalDecisions.CrystalReports.Engine.ReportDocument.Export()
   en CrystalReportsNinja.ReportProcessor.PerformOutput()
   en CrystalReportsNinja.ReportProcessor.Run()
17-07-2023      20:50:38        ====================================================================
Exception: No se pudo abrir la conexión.
reporte 20284_15032_{2FF0929E-00EF-4E59-93A2-E2F892898C23}.rpt
Inner Exception: System.Runtime.InteropServices.COMException (0x800002F4): No se pudo abrir la conexión.
reporte 20284_15032_{2FF0929E-00EF-4E59-93A2-E2F892898C23}.rpt
   en CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   en CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
```

[https://i.ibb.co/Ns8c9rp/Captura-de-pantalla-2023-07-17-211439.png](url)
